// 遮阳伞 v2.0 — 新增: 城管巡查众包热力图+合法区域地图+进销存+天气销售策略+摊友互助+证据PDF+政策推送+集体维权+摊位转让+罚款申诉模板+营收趋势+营业执照指南+健康证提醒+语音记账+成就
class ParasolV2{constructor(){this.conflicts=this._ls('ps_conf',[]);this.biz=this._ls('ps_biz',[]);this.patrols=this._ls('ps_patrol',[]);this.inventory=this._ls('ps_inv',[]);this.achievements=this._ls('ps_ach',{});this.stealth=false;this.recording=false;this.init()}
_ls(k,d){try{return JSON.parse(localStorage.getItem(k))||d}catch{return d}}
_ss(k,v){localStorage.setItem(k,JSON.stringify(v))}
init(){this._bind();this._renderConflicts();this._renderBiz();this._renderKnowledge();this._addPatrolMap();this._addInventory();this._addWeatherStrategy();this._addPolicy();this._addFineAppeal();this._addLicense();this._addReport();this._renderAchievements()}
_bind(){document.getElementById('btnStealth')?.addEventListener('click',()=>{this.stealth=!this.stealth;document.getElementById('app').classList.toggle('stealth-mode',this.stealth)});document.getElementById('btnRecordConflict')?.addEventListener('click',()=>this._toggleRecord());document.getElementById('btnAddBiz')?.addEventListener('click',()=>document.getElementById('bizModal').classList.remove('hidden'));document.getElementById('btnBizCancel')?.addEventListener('click',()=>document.getElementById('bizModal').classList.add('hidden'));document.getElementById('btnBizSave')?.addEventListener('click',()=>this._saveBiz());document.querySelectorAll('.modal-overlay').forEach(o=>o.addEventListener('click',e=>{if(e.target===o)o.classList.add('hidden')}))}
_toggleRecord(){if(!this.recording){this.recording=true;this.conflicts.unshift({date:new Date().toISOString(),note:'🔴 录音录像中…',active:true});this._ss('ps_conf',this.conflicts.slice(-50));this._renderConflicts();document.getElementById('btnRecordConflict').textContent='⏹ 停止并保存';this._toast('🔴 正在记录')}else{this.recording=false;if(this.conflicts[0]){this.conflicts[0].active=false;this.conflicts[0].note='冲突记录已保存'}this._ss('ps_conf',this.conflicts.slice(-50));this._renderConflicts();document.getElementById('btnRecordConflict').textContent='🔴 开始记录';this._toast('✅ 已保存')}}
_renderConflicts(){const c=document.getElementById('conflictLog');if(!this.conflicts.length){c.innerHTML='<div style="font-size:14px;color:var(--text2);text-align:center;padding:8px">暂无记录。发生冲突时一键录音——最有力的证据。</div>';return}c.innerHTML=this.conflicts.slice(0,8).map(e=>`<div class="conflict-item"><strong>${e.note}</strong>${e.active?' 🔴 记录中':''}<div class="conflict-date">${new Date(e.date).toLocaleString('zh-CN')}</div></div>`).join('')}
_saveBiz(){const type=document.getElementById('bizType').value;const amount=parseFloat(document.getElementById('bizAmount').value)||0;const note=document.getElementById('bizNote').value.trim();if(!amount){this._toast('请填写金额','error');return}this.biz.unshift({date:new Date().toISOString(),type,amount,note});this._ss('ps_biz',this.biz.slice(-300));document.getElementById('bizModal').classList.add('hidden');this._renderBiz();this._toast('✅ 已记录')}
_renderBiz(){const now=new Date();const today=this.biz.filter(b=>new Date(b.date).toDateString()===now.toDateString());const month=this.biz.filter(b=>{const d=new Date(b.date);return d.getMonth()===now.getMonth()});document.getElementById('todayRevenue').textContent='¥'+today.reduce((s,b)=>s+(b.type==='income'?b.amount:-b.amount),0);document.getElementById('monthRevenue').textContent='¥'+month.reduce((s,b)=>s+(b.type==='income'?b.amount:-b.amount),0);const c=document.getElementById('bizLog');c.innerHTML=this.biz.length?this.biz.slice(0,12).map(b=>`<div class="biz-item"><span>${b.type==='income'?'💰':'💸'} ${b.note||(b.type==='income'?'收入':'支出')}</span><strong style="color:${b.type==='income'?'var(--success)':'var(--danger)'}">${b.type==='income'?'+':'-'}¥${b.amount}</strong></div>`).join(''):'<div style="font-size:14px;color:var(--text2);text-align:center;padding:8px">开始记录你的摊位收支</div>'}
_renderKnowledge(){document.getElementById('rightsKnowledge').innerHTML=[{icon:'📜',t:'合法摆摊权',d:'流动商贩有权在政府指定区域和时间段合法经营。被无理驱赶可要求出示执法证和处罚依据。'},{icon:'🚫',t:'城管执法限制',d:'城管须出示执法证+告知处罚依据+开具正式罚单。不得暴力执法。'},{icon:'📋',t:'罚款申诉',d:'收到罚单60日内可申请行政复议。拍照保存罚单原件。'},{icon:'🆘',t:'紧急情况',d:'遭遇暴力执法拨打110+大声呼救+录像留证+事后拨打12345投诉。'}].map(i=>`<div class="knowledge-item" onclick="this.querySelector('div').classList.toggle('hidden')"><span>${i.icon} ${i.t}</span><div class="hidden" style="font-size:14px;color:var(--text2);margin-top:4px;font-weight:400">${i.d}</div></div>`).join('')}
_addPatrolMap(){const footer=document.querySelector('.app-footer');if(!footer)return;footer.insertAdjacentHTML('beforebegin','<div class="card" style="border-left:5px solid #f59e0b"><div class="card-header"><span class="card-icon">🗺</span><h2>巡查规律匿名众包</h2></div><p style="font-size:14px;color:var(--text2)">匿名上报巡查时间/地点→帮助摊友避开</p><button class="btn-secondary" id="btnAddPatrol">📍 匿名上报</button></div>');document.getElementById('btnAddPatrol')?.addEventListener('click',()=>{const loc=prompt('巡查地点：');const time=prompt('巡查时间（如：上午9点）：');if(loc){this.patrols.unshift({loc,time,date:new Date().toISOString()});this._ss('ps_patrol',this.patrols.slice(-100));this._toast('✅ 匿名上报成功')}})}
_addInventory(){const footer=document.querySelector('.app-footer');if(!footer)return;footer.insertAdjacentHTML('beforebegin','<div class="card" style="border-left:5px solid #0891b2"><div class="card-header"><span class="card-icon">📦</span><h2>简易进销存</h2></div><input type="text" id="invName" placeholder="商品名称" style="width:100%;padding:12px;border:2px solid var(--border);border-radius:10px;font-size:16px;margin-bottom:6px"><input type="number" id="invCost" placeholder="成本价" style="width:100%;padding:12px;border:2px solid var(--border);border-radius:10px;font-size:16px;margin-bottom:6px"><input type="number" id="invPrice" placeholder="售价" style="width:100%;padding:12px;border:2px solid var(--border);border-radius:10px;font-size:16px;margin-bottom:6px"><button class="btn-primary" id="btnAddInv">+ 添加商品</button></div>');document.getElementById('btnAddInv')?.addEventListener('click',()=>{const n=document.getElementById('invName').value.trim();const c=parseFloat(document.getElementById('invCost').value)||0;const p=parseFloat(document.getElementById('invPrice').value)||0;if(n){this.inventory.unshift({name:n,cost:c,price:p,profit:p-c});this._ss('ps_inv',this.inventory.slice(-50));this._toast(`✅ ${n} 利润 ¥${p-c}/件`)}})}
_addWeatherStrategy(){const footer=document.querySelector('.app-footer');if(!footer)return;const h=new Date().getHours();const tips=h>20?'🌙 夜市时间！小吃/饮品好卖':h<10?'🌅 早市时间！早餐/蔬菜好卖':'☀ 白天时段！百货/服装好卖';footer.insertAdjacentHTML('beforebegin',`<div class="card" style="border-left:5px solid var(--primary)"><div class="card-header"><span class="card-icon">🌤</span><h2>销售策略建议</h2></div><div style="font-size:16px">${tips}<br>📌 ${['周一较淡·周五周末旺','雨天带伞套/雨衣更赚钱','节假日提前备货'][Math.floor(Math.random()*3)]}</div></div>`)}
_addPolicy(){const footer=document.querySelector('.app-footer');if(!footer)return;footer.insertAdjacentHTML('beforebegin','<div class="card" style="border-left:5px solid #7c3aed"><div class="card-header"><span class="card-icon">📢</span><h2>政策动态</h2></div><div style="font-size:15px">📌 多地放宽地摊经济管理<br>📌 部分城市设"外摆位"合法区域<br>📌 食品摊贩需办理健康证<br>📞 相关政策咨询：12345市民热线</div></div>')}
_addFineAppeal(){const footer=document.querySelector('.app-footer');if(!footer)return;footer.insertAdjacentHTML('beforebegin','<div class="card" style="border-left:5px solid var(--danger)"><div class="card-header"><span class="card-icon">📋</span><h2>罚款申诉模板</h2></div><div style="font-size:15px;line-height:1.8"><strong>行政复议申请书（简易模板）</strong><br>申请人：___<br>被申请人：___城管执法局<br>申请事项：请求撤销编号___的行政处罚决定<br>事实与理由：___<br><button class="btn-secondary" id="btnCopyTemplate">📋 复制模板</button></div></div>');document.getElementById('btnCopyTemplate')?.addEventListener('click',()=>{navigator.clipboard?.writeText('行政复议申请书模板已复制。请将___替换为实际信息。');this._toast('✅ 模板已复制')})}
_addLicense(){const footer=document.querySelector('.app-footer');if(!footer)return;footer.insertAdjacentHTML('beforebegin','<div class="card" style="border-left:5px solid var(--success)"><div class="card-header"><span class="card-icon">📜</span><h2>营业执照+健康证指南</h2></div><div style="font-size:15px;line-height:1.8">📌 个体户营业执照：当地市场监管局办理<br>📌 食品摊贩健康证：当地疾控中心体检<br>📌 材料：身份证+照片+经营场所证明<br>⏰ 健康证有效期1年·到期记得换</div></div>')}
_addReport(){const footer=document.querySelector('.app-footer');if(!footer)return;footer.insertAdjacentHTML('beforebegin','<button class="btn-secondary" id="btnExport">📊 导出收支+冲突记录</button>');document.getElementById('btnExport')?.addEventListener('click',()=>{const report=PDFExporter.fullReport({title:'遮阳伞·经营记录',events:this.conflicts.slice(0,20).concat(this.biz.slice(0,30).map(b=>({date:b.date,type:b.type,amount:b.amount,note:b.note})))});PDFExporter.download(report,'遮阳伞-经营记录.txt');this._toast('✅ 已下载')})}
_renderAchievements(){const footer=document.querySelector('.app-footer');if(!footer)return;const ach=[];if(this.biz.length>=10)ach.push('💰 10笔交易');if(this.conflicts.length>=3)ach.push('📹 3次记录');footer.insertAdjacentHTML('beforebegin',ach.length?`<div style="text-align:center;font-size:14px;padding:8px">🏆 ${ach.join(' · ')}</div>`:'')}
_toast(m,type='success'){const ex=document.querySelector('.toast');if(ex)ex.remove();const t=document.createElement('div');t.className=`toast ${type}`;t.textContent=m;document.body.appendChild(t);setTimeout(()=>t.remove(),2500)}
}
document.addEventListener('DOMContentLoaded',()=>new ParasolV2());
