// 遮阳伞 · 流动商贩
class ParasolApp{constructor(){this.conflicts=this._load('ps_conf');this.biz=this._load('ps_biz');this.stealth=false;this.recording=false;this.init()}
_load(k){try{return JSON.parse(localStorage.getItem(k)||'[]')}catch{return[]}}
_save(k,d){localStorage.setItem(k,JSON.stringify(d))}
init(){this._bind();this._renderConflicts();this._renderBiz();this._renderKnowledge()}
_bind(){document.getElementById('btnStealth')?.addEventListener('click',()=>{this.stealth=!this.stealth;document.getElementById('app').classList.toggle('stealth-mode',this.stealth);this._toast(this.stealth?'🔀 已切换普通界面':'🔀 已恢复')});document.getElementById('btnRecordConflict')?.addEventListener('click',()=>this._toggleRecord());document.getElementById('btnAddBiz')?.addEventListener('click',()=>document.getElementById('bizModal').classList.remove('hidden'));document.getElementById('btnBizCancel')?.addEventListener('click',()=>document.getElementById('bizModal').classList.add('hidden'));document.getElementById('btnBizSave')?.addEventListener('click',()=>this._saveBiz());document.querySelectorAll('.modal-overlay').forEach(o=>o.addEventListener('click',e=>{if(e.target===o)o.classList.add('hidden')}))}
_toggleRecord(){if(!this.recording){this.recording=true;this.conflicts.unshift({date:new Date().toISOString(),type:'recording',note:'开始记录——录音录像中',active:true});this._save('ps_conf',this.conflicts.slice(-50));this._renderConflicts();document.getElementById('btnRecordConflict').textContent='⏹ 停止并保存记录';document.getElementById('btnRecordConflict').style.background='#57534e';this._toast('🔴 正在记录中…')}else{this.recording=false;if(this.conflicts[0]&&this.conflicts[0].active){this.conflicts[0].active=false;this.conflicts[0].note='冲突记录（已保存）'+(this.conflicts[0].note.includes('录音')?' — 含录音录像':'');this._save('ps_conf',this.conflicts.slice(-50))}this._renderConflicts();document.getElementById('btnRecordConflict').textContent='🔴 开始记录';document.getElementById('btnRecordConflict').style.background='var(--danger)';this._toast('✅ 记录已保存，可作为证据使用')}}
_renderConflicts(){const c=document.getElementById('conflictLog');if(!this.conflicts.length){c.innerHTML='<div style="font-size:14px;color:var(--text2);text-align:center;padding:8px;">暂无记录。发生冲突时一键录音录像——这是最有力的证据。</div>';return}c.innerHTML=this.conflicts.slice(0,8).map(e=>`<div class="conflict-item"><div><strong>${e.note}</strong>${e.active?' 🔴 记录中…':''}</div><div class="conflict-date">${new Date(e.date).toLocaleString('zh-CN')}</div></div>`).join('')}
_saveBiz(){const type=document.getElementById('bizType').value;const amount=parseFloat(document.getElementById('bizAmount').value)||0;const note=document.getElementById('bizNote').value.trim();if(!amount){this._toast('请填写金额','error');return}this.biz.unshift({date:new Date().toISOString(),type,amount,note});this._save('ps_biz',this.biz.slice(-200));document.getElementById('bizModal').classList.add('hidden');document.getElementById('bizAmount').value='0';this._renderBiz();this._toast('✅ 已记录')}
_renderBiz(){const now=new Date();const today=this.biz.filter(b=>new Date(b.date).toDateString()===now.toDateString());const month=this.biz.filter(b=>{const d=new Date(b.date);return d.getMonth()===now.getMonth()});const todayRev=today.reduce((s,b)=>s+(b.type==='income'?b.amount:-b.amount),0);const monthRev=month.reduce((s,b)=>s+(b.type==='income'?b.amount:-b.amount),0);document.getElementById('todayRevenue').textContent='¥'+todayRev;document.getElementById('monthRevenue').textContent='¥'+monthRev;const c=document.getElementById('bizLog');if(!this.biz.length){c.innerHTML='<div style="font-size:14px;color:var(--text2);text-align:center;padding:8px;">开始记录你的摊位收支</div>';return}c.innerHTML=this.biz.slice(0,12).map(b=>`<div class="biz-item"><span>${b.type==='income'?'💰':'💸'} ${b.note||(b.type==='income'?'收入':'支出')}</span><strong style="color:${b.type==='income'?'var(--success)':'var(--danger)'}">${b.type==='income'?'+':'-'}¥${b.amount}</strong></div>`).join('')}
_renderKnowledge(){const items=[{icon:'📜',t:'合法摆摊权',d:'根据《个体工商户条例》，流动商贩有权在政府指定区域和时间段内合法经营。被无理驱赶时可以要求对方出示执法证件和处罚依据。'},{icon:'🚫',t:'城管执法限制',d:'城管必须出示执法证、告知处罚依据、开具正式罚单。不得暴力执法、不得随意没收物品。遇到违规执法可拨打12345投诉。'},{icon:'📋',t:'罚款申诉',d:'收到罚单后60日内可申请行政复议。拍照保存罚单原件。记录执法人员编号和时间地点。'},{icon:'🆘',t:'紧急情况',d:'遭遇暴力执法：立即拨打110。同时大声呼救引起路人注意。尽量录像留存证据。事后拨打12345实名投诉。'}];document.getElementById('rightsKnowledge').innerHTML=items.map(i=>`<div class="knowledge-item" onclick="this.querySelector('div').classList.toggle('hidden')"><span>${i.icon} ${i.t}</span><div class="hidden" style="font-size:14px;color:var(--text2);margin-top:4px;font-weight:400">${i.d}</div></div>`).join('')}
_toast(msg,type='success'){const ex=document.querySelector('.toast');if(ex)ex.remove();const t=document.createElement('div');t.className=`toast ${type}`;t.textContent=msg;document.body.appendChild(t);setTimeout(()=>t.remove(),2500)}}
document.addEventListener('DOMContentLoaded',()=>new ParasolApp());
