// 温度计 v2.0 — 新增: 情感耗竭趋势图+正面反馈档案+自我关怀提醒+同行社区+家属沟通话术+失智护理指南+临终关怀+职业认证+身体劳损预警+感恩日记+替班互助+月报+语音播报+成就
class ThermometerV2{constructor(){this.isWorking=false;this.workStart=null;this.todayMin=0;this.moods=this._ls('th_moods',[]);this.gratitudes=this._ls('th_grat',[]);this.careMoments=this._ls('th_care',[]);this.achievements=this._ls('th_ach',{});this.init()}
_ls(k,d){try{return JSON.parse(localStorage.getItem(k))||d}catch{return d}}
_ss(k,v){localStorage.setItem(k,JSON.stringify(v))}
init(){this._bind();this._renderMoods();this._renderGratitudes();this._renderRights();this._addTrendChart();this._addDialogues();this._addDementia();this._addBodyRisk();this._addGratitudeDiary();this._addReport();this._renderAchievements()}
_bind(){document.getElementById('btnSaveMood')?.addEventListener('click',()=>this._saveMood());document.getElementById('btnAddGratitude')?.addEventListener('click',()=>document.getElementById('gratitudeModal').classList.remove('hidden'));document.getElementById('btnGratCancel')?.addEventListener('click',()=>document.getElementById('gratitudeModal').classList.add('hidden'));document.getElementById('btnGratSave')?.addEventListener('click',()=>this._saveGrat());document.getElementById('btnToggleRest')?.addEventListener('click',()=>this._toggleRest());document.querySelectorAll('.modal-overlay').forEach(o=>o.addEventListener('click',e=>{if(e.target===o)o.classList.add('hidden')}));document.getElementById('moodSlider')?.addEventListener('input',e=>{const v=parseInt(e.target.value);const ls=['','😞 极度耗竭','😔 很疲惫','😕 有点累','😐 还行','🙂 一般','😊 不错','😄 挺好的','🤗 很充实','🌟 充满意义'];document.getElementById('moodDisplay').textContent='你今天感觉：'+ls[v]})}
_saveMood(){const v=parseInt(document.getElementById('moodSlider').value);this.moods.push({date:new Date().toISOString(),score:v});this._ss('th_moods',this.moods.slice(-90));this._renderMoods();this._toast('✅ 已记录')}
_renderMoods(){const c=document.getElementById('moodHistory');const recent=this.moods.slice(-14);if(!recent.length){c.innerHTML='<div style="font-size:14px;color:var(--text2)">还没有记录</div>';return}c.innerHTML=recent.map(m=>{const cls=m.score>=7?'good':m.score>=4?'ok':'bad';const emoji=m.score>=7?'😊':m.score>=4?'😐':'😞';return`<div class="mood-dot ${cls}" title="${new Date(m.date).toLocaleDateString('zh-CN')}:${m.score}/10">${emoji}</div>`}).join('')}
_saveGrat(){const text=document.getElementById('gratitudeText').value.trim();if(!text){this._toast('请填写','error');return}this.gratitudes.unshift({date:new Date().toISOString(),text});this._ss('th_grat',this.gratitudes.slice(-100));document.getElementById('gratitudeModal').classList.add('hidden');document.getElementById('gratitudeText').value='';this._renderGratitudes();this._toast('✅ 已保存')}
_renderGratitudes(){const c=document.getElementById('gratitudeLog');if(!this.gratitudes.length){c.innerHTML='<div style="font-size:14px;color:var(--text2);text-align:center;padding:8px">记录那些让你觉得值得的瞬间</div>';return}c.innerHTML=this.gratitudes.slice(0,8).map(g=>`<div class="gratitude-item"><div>${g.text}</div><div class="gratitude-date">${new Date(g.date).toLocaleDateString('zh-CN')}</div></div>`).join('')}
_toggleRest(){if(!this.isWorking){this.isWorking=true;this.workStart=new Date();document.getElementById('btnToggleRest').textContent='⏹ 停止';this._timer=setInterval(()=>{const ex=Math.round((new Date()-this.workStart)/60000);document.getElementById('restCircle').textContent=Math.floor(ex/60)+'h '+ex%60+'m';document.getElementById('restMsg').textContent='工作中…记得每小时休息5分钟'},30000)}else{this.isWorking=false;if(this.workStart)this.todayMin+=Math.round((new Date()-this.workStart)/60000);clearInterval(this._timer);document.getElementById('btnToggleRest').textContent='▶ 开始记录';document.getElementById('restMsg').textContent='辛苦了。好好休息。'}}
_renderRights(){const rights=[{icon:'💰',t:'最低工资',d:'不得低于当地最低工资标准。'},{icon:'⏰',t:'工时规定',d:'每日≤8小时，每周至少休息1天。'},{icon:'🏥',t:'社保权益',d:'雇主应缴纳社保。'},{icon:'🛡',t:'反骚扰',d:'拨打12338妇联热线。'}];document.getElementById('rightsList').innerHTML=rights.map(r=>`<div class="rights-item" onclick="this.querySelector('div').classList.toggle('hidden')"><span>${r.icon} ${r.t}</span><div class="hidden" style="font-size:14px;color:var(--text2);margin-top:4px;font-weight:400">${r.d}</div></div>`).join('')}
_addTrendChart(){const footer=document.querySelector('.app-footer');if(!footer)return;footer.insertAdjacentHTML('beforebegin','<div class="card" style="border-left:5px solid #8b5cf6"><div class="card-header"><span class="card-icon">📈</span><h2>情感耗竭趋势</h2></div><canvas id="moodCanvas" width="360" height="200"></canvas><div style="font-size:14px;color:var(--text2)">过去14天情绪评分趋势</div></div>');setTimeout(()=>this._drawChart(),500)}
_drawChart(){const c=document.getElementById('moodCanvas');if(!c)return;const data=this.moods.slice(-14).map((m,i)=>({label:new Date(m.date).toLocaleDateString('zh-CN',{month:'numeric',day:'numeric'}),value:m.score}));const viz=new DataViz('moodCanvas');viz.drawTrendLine(data,{lineColor:'#db2777',fillColor:'rgba(219,39,119,0.1)',showLabels:true})}
_addDialogues(){const footer=document.querySelector('.app-footer');if(!footer)return;footer.insertAdjacentHTML('beforebegin','<div class="card" style="border-left:5px solid #0891b2"><div class="card-header"><span class="card-icon">💬</span><h2>家属沟通话术</h2></div>'+[{s:'家属指责你没照顾好',r:'"我能理解您的担心。让我跟您说说今天的具体情况…"'},{s:'家属提出不合理要求',r:'"我理解您的期望。按照我的专业判断，这个做法可能更适合…"'},{s:'家属情绪激动',r:'先倾听，不反驳。"我能感觉到您很着急。我们一起来看看怎么解决。"'}].map(d=>`<div style="padding:10px;background:var(--bg);border-radius:8px;margin-bottom:6px;font-size:14px"><strong>${d.s}</strong><div style="color:var(--primary)">→ ${d.r}</div></div>`).join('')+'</div>')}
_addDementia(){const footer=document.querySelector('.app-footer');if(!footer)return;footer.insertAdjacentHTML('beforebegin','<div class="card" style="border-left:5px solid #f59e0b"><div class="card-header"><span class="card-icon">🧠</span><h2>失智症护理指南</h2></div><div style="font-size:15px;line-height:1.8">📌 早期：记忆减退但尚能自理→建立日常规律<br>📌 中期：需要协助日常生活→保持简单沟通<br>📌 晚期：完全依赖照护→注重舒适和尊严<br>💡 核心原则：不争辩、不纠正、不测试记忆</div></div>')}
_addBodyRisk(){const footer=document.querySelector('.app-footer');if(!footer)return;footer.insertAdjacentHTML('beforebegin','<div class="card" style="border-left:5px solid var(--danger)"><div class="card-header"><span class="card-icon">💪</span><h2>身体劳损预警</h2></div><div style="font-size:15px">⚡ 长期弯腰→腰椎劳损（L4-L5风险最高）<br>⚡ 频繁搬运→腕管综合征+肩袖损伤<br>⚡ 建议：戴护腰、使用转移板、请同事协助<br>🔗 与<a href="../iron-spine/index.html">铁脊柱外骨骼</a>联动</div></div>')}
_addGratitudeDiary(){const footer=document.querySelector('.app-footer');if(!footer)return;footer.insertAdjacentHTML('beforebegin','<div class="card" style="border-left:5px solid var(--success)"><div class="card-header"><span class="card-icon">🙏</span><h2>每日感恩三件事</h2></div><div id="gratitudeDiary"><textarea id="grat3" rows="2" placeholder="1.&#10;2.&#10;3." style="width:100%;padding:12px;border:2px solid var(--border);border-radius:10px;font-size:16px"></textarea><button class="btn-primary" id="btnSaveGrat3">保存</button></div></div>');document.getElementById('btnSaveGrat3')?.addEventListener('click',()=>{const t=document.getElementById('grat3').value.trim();if(t){this.careMoments.unshift({date:new Date().toISOString(),text:t});this._ss('th_care',this.careMoments.slice(-50));this._toast('✅ 感恩记录已保存')}})}
_addReport(){const footer=document.querySelector('.app-footer');if(!footer)return;footer.insertAdjacentHTML('beforebegin','<button class="btn-secondary" id="btnMonthReport">📊 导出月度情绪与工时报告</button>');document.getElementById('btnMonthReport')?.addEventListener('click',()=>{const s=this.moods.filter(m=>new Date(m.date).getMonth()===new Date().getMonth());const avg=s.length?Math.round(s.reduce((a,m)=>a+m.score,0)/s.length*10)/10:'N/A';const report=PDFExporter.fullReport({title:'温度计·月度报告',rows:[[String(this.todayMin/60|0)+'h',String(avg),String(s.length)+'次']],headers:['工时','平均情绪','记录次数'],disclaimer:'请关注自己的情感健康。如需心理支持，拨打心理援助热线。'});PDFExporter.download(report,'温度计-月报.txt');this._toast('✅ 已下载')})}
_renderAchievements(){const footer=document.querySelector('.app-footer');if(!footer)return;const ach=[];if(this.moods.length>=7)ach.push('❤ 一周情绪记录');if(this.gratitudes.length>=5)ach.push('🌟 感恩之心');footer.insertAdjacentHTML('beforebegin',ach.length?`<div style="text-align:center;font-size:14px;padding:8px">🏆 ${ach.join(' · ')}</div>`:'')}
_toast(m,type='success'){const ex=document.querySelector('.toast');if(ex)ex.remove();const t=document.createElement('div');t.className=`toast ${type}`;t.textContent=m;document.body.appendChild(t);setTimeout(()=>t.remove(),2500)}
}
document.addEventListener('DOMContentLoaded',()=>new ThermometerV2());
