// 温度计 · 养老护理员
class ThermometerApp{constructor(){this.isWorking=false;this.workStart=null;this.todayMin=0;this.moods=this._load('th_moods');this.gratitudes=this._load('th_grat');this.init()}
_load(k){try{return JSON.parse(localStorage.getItem(k)||'[]')}catch{return[]}}
_save(k,d){localStorage.setItem(k,JSON.stringify(d))}
init(){this._bind();this._renderMoods();this._renderGratitudes();this._renderRights()}
_bind(){document.getElementById('btnSaveMood')?.addEventListener('click',()=>this._saveMood());document.getElementById('btnAddGratitude')?.addEventListener('click',()=>document.getElementById('gratitudeModal').classList.remove('hidden'));document.getElementById('btnGratCancel')?.addEventListener('click',()=>document.getElementById('gratitudeModal').classList.add('hidden'));document.getElementById('btnGratSave')?.addEventListener('click',()=>this._saveGrat());document.getElementById('btnToggleRest')?.addEventListener('click',()=>this._toggleRest());document.querySelectorAll('.modal-overlay').forEach(o=>o.addEventListener('click',e=>{if(e.target===o)o.classList.add('hidden')}));document.getElementById('moodSlider')?.addEventListener('input',e=>{const v=parseInt(e.target.value);const labels=['','😞 极度耗竭','😔 很疲惫','😕 有点累','😐 还行','🙂 一般般','😊 还不错','😄 挺好的','🤗 很充实','🌟 充满意义'];document.getElementById('moodDisplay').textContent='你今天感觉：'+labels[v]})}
_saveMood(){const v=parseInt(document.getElementById('moodSlider').value);this.moods.push({date:new Date().toISOString(),score:v});this._save('th_moods',this.moods.slice(-30));this._renderMoods();this._toast('✅ 心情已记录')}
_renderMoods(){const container=document.getElementById('moodHistory');const recent=this.moods.slice(-14);if(!recent.length){container.innerHTML='<div style="font-size:14px;color:var(--text2)">还没有记录</div>';return}container.innerHTML=recent.map(m=>{const cls=m.score>=7?'good':m.score>=4?'ok':'bad';const emoji=m.score>=7?'😊':m.score>=4?'😐':'😞';return`<div class="mood-dot ${cls}" title="${new Date(m.date).toLocaleDateString('zh-CN')}: ${m.score}/10">${emoji}</div>`}).join('')}
_saveGrat(){const text=document.getElementById('gratitudeText').value.trim();if(!text){this._toast('请填写内容','error');return}this.gratitudes.unshift({date:new Date().toISOString(),text});this._save('th_grat',this.gratitudes.slice(-50));document.getElementById('gratitudeModal').classList.add('hidden');document.getElementById('gratitudeText').value='';this._renderGratitudes();this._toast('✅ 美好瞬间已保存')}
_renderGratitudes(){const c=document.getElementById('gratitudeLog');if(!this.gratitudes.length){c.innerHTML='<div style="font-size:14px;color:var(--text2);text-align:center;padding:8px;">记录那些让你觉得值得的瞬间——对抗情感耗竭最好的方式</div>';return}c.innerHTML=this.gratitudes.slice(0,8).map(g=>`<div class="gratitude-item"><div>${g.text}</div><div class="gratitude-date">${new Date(g.date).toLocaleDateString('zh-CN')}</div></div>`).join('')}
_toggleRest(){if(!this.isWorking){this.isWorking=true;this.workStart=new Date();document.getElementById('btnToggleRest').textContent='⏹ 停止记录';document.getElementById('restMsg').textContent='工作中…记得每小时休息5分钟';this._timer=setInterval(()=>{const ex=Math.round((new Date()-this.workStart)/60000);document.getElementById('restCircle').textContent=Math.floor(ex/60)+'h '+ex%60+'m'},30000)}else{this.isWorking=false;if(this.workStart)this.todayMin+=Math.round((new Date()-this.workStart)/60000);clearInterval(this._timer);document.getElementById('btnToggleRest').textContent='▶ 开始记录工时';document.getElementById('restMsg').textContent='今天工作了'+Math.floor(this.todayMin/60)+'小时'+this.todayMin%60+'分钟。辛苦了，好好休息。'}}
_renderRights(){const rights=[{icon:'💰',t:'最低工资标准',d:'养老护理员月工资不得低于当地最低工资标准。北京2420元/月。'},{icon:'⏰',t:'工时规定',d:'每日不超过8小时，每周至少休息1天。加班应付1.5-3倍工资。'},{icon:'🏥',t:'社保权益',d:'雇主应为你缴纳社保。不缴是违法的，可向社保部门投诉。'},{icon:'🛡',t:'反骚扰保护',d:'任何形式的骚扰都是违法的。拨打12338妇联热线求助。'}];document.getElementById('rightsList').innerHTML=rights.map(r=>`<div class="rights-item" onclick="this.querySelector('div').classList.toggle('hidden')"><span>${r.icon} ${r.t}</span><div class="hidden" style="font-size:14px;color:var(--text2);margin-top:4px;font-weight:400">${r.d}</div></div>`).join('')}
_toast(msg,type='success'){const ex=document.querySelector('.toast');if(ex)ex.remove();const t=document.createElement('div');t.className=`toast ${type}`;t.textContent=msg;document.body.appendChild(t);setTimeout(()=>t.remove(),2500)}}
document.addEventListener('DOMContentLoaded',()=>new ThermometerApp());
