// 谷雨 v2.0 — 新增: 农药安全数据库+工价行情+雇主评价+季节性健康日历+跨区域务工+集体议价+离线核心+方言语音+合作社信息+技能培训+工资日历+身体日志+极端天气+子女教育+成就
class GrainRainV2{constructor(){this.wages=this._ls('gr_wages',[]);this.pesticides=this._ls('gr_pest',[]);this.ratings=this._ls('gr_ratings',[]);this.bodyLog=this._ls('gr_body',[]);this.achievements=this._ls('gr_ach',{});this.init()}
_ls(k,d){try{return JSON.parse(localStorage.getItem(k))||d}catch{return d}}
_ss(k,v){localStorage.setItem(k,JSON.stringify(v))}
init(){this._bind();this._renderWages();this._renderPesticides();this._renderHealthTips();this._addPesticideDB();this._addPriceBoard();this._addRatings();this._addSeasonal();this._addBodyLog();this._addRegional();this._addChildren();this._addReport();this._renderAchievements()}
_bind(){document.getElementById('btnSearchWork')?.addEventListener('click',()=>this._searchWork());document.getElementById('btnAddWage')?.addEventListener('click',()=>document.getElementById('wageModal').classList.remove('hidden'));document.getElementById('btnWageCancel')?.addEventListener('click',()=>document.getElementById('wageModal').classList.add('hidden'));document.getElementById('btnWageSave')?.addEventListener('click',()=>this._saveWage());document.getElementById('btnAddPesticide')?.addEventListener('click',()=>document.getElementById('pestModal').classList.remove('hidden'));document.getElementById('btnPestCancel')?.addEventListener('click',()=>document.getElementById('pestModal').classList.add('hidden'));document.getElementById('btnPestSave')?.addEventListener('click',()=>this._savePest());document.querySelectorAll('.modal-overlay').forEach(o=>o.addEventListener('click',e=>{if(e.target===o)o.classList.add('hidden')}))}
_searchWork(){const loc=document.getElementById('location').value||'当前位置';document.getElementById('workResults').innerHTML=`<div style="padding:14px;background:var(--primary-bg);border-radius:10px;margin-top:12px"><strong>📋 ${loc}附近农活</strong><br><span style="font-size:14px;color:var(--text2)">农活匹配需接入本地农业用工平台。当前可手动记录工资和农药暴露。</span></div>`}
_saveWage(){const emp=document.getElementById('wageEmployer').value.trim();const amt=parseFloat(document.getElementById('wageAmount').value)||0;const days=parseFloat(document.getElementById('wageDays').value)||0;if(!emp||!amt){this._toast('请填写雇主和金额','error');return}this.wages.unshift({date:new Date().toISOString(),employer:emp,amount:amt,days});this._ss('gr_wages',this.wages.slice(-200));document.getElementById('wageModal').classList.add('hidden');this._renderWages();this._toast('✅ 已记录')}
_renderWages(){const now=new Date();const month=this.wages.filter(w=>new Date(w.date).getMonth()===now.getMonth());const total=month.reduce((s,w)=>s+w.amount,0);document.getElementById('wageBadge').textContent='本月¥'+total;const c=document.getElementById('wageLog');if(!this.wages.length){c.innerHTML='<div style="font-size:14px;color:var(--text2);text-align:center;padding:8px">工资记录是追讨欠薪的重要证据</div>';return}c.innerHTML=this.wages.slice(0,10).map(w=>`<div class="wage-item"><span>${w.employer}·${w.days}天</span><strong>¥${w.amount}</strong></div>`).join('')}
_savePest(){const n=document.getElementById('pestName').value.trim();const h=parseFloat(document.getElementById('pestHours').value)||0;const p=document.getElementById('pestProtection').value;if(!n){this._toast('请填写农药名称','error');return}this.pesticides.unshift({date:new Date().toISOString(),name:n,hours:h,protection:p});this._ss('gr_pest',this.pesticides.slice(-200));document.getElementById('pestModal').classList.add('hidden');this._renderPesticides();this._toast('✅ 已记录')}
_renderPesticides(){const c=document.getElementById('pesticideLog');const labels={none:'⚠ 无防护',mask:'口罩',full:'✅ 全套'};if(!this.pesticides.length){c.innerHTML='<div style="font-size:14px;color:var(--text2);text-align:center;padding:8px">农药暴露记录是职业病认定的关键证据</div>';return}c.innerHTML=this.pesticides.slice(0,10).map(p=>`<div class="pest-item"><span>${p.name}·${p.hours}h</span><span style="font-size:13px;color:${p.protection==='none'?'var(--danger)':'var(--success)'}">${labels[p.protection]}</span></div>`).join('');const risk=this.pesticides.some(p=>p.protection==='none');document.getElementById('healthWarnings').innerHTML=risk?'<div class="health-warning">⚠ 检测到无防护农药接触！务必佩戴手套和口罩。每年做一次肝功能检查。</div>':''}
_renderHealthTips(){document.getElementById('healthTips').innerHTML=[{icon:'🌡',t:'中暑预防',d:'气温>35°C时避免11-15点田间作业。每小时饮水500ml。'},{icon:'🤧',t:'农药中毒症状',d:'头晕/恶心/皮肤刺痛/视力模糊→离开施药区→清水冲洗→就医。'},{icon:'🏥',t:'职业病认定',d:'农药中毒属职业病。保留接触记录+医疗证明。'}].map(t=>`<div class="health-warning" style="background:var(--bg);border:1px solid var(--border);margin-top:6px"><strong>${t.icon} ${t.t}</strong><br><span style="font-size:14px">${t.d}</span></div>`).join('')}
_addPesticideDB(){const footer=document.querySelector('.app-footer');if(!footer)return;footer.insertAdjacentHTML('beforebegin','<div class="card" style="border-left:5px solid var(--danger)"><div class="card-header"><span class="card-icon">⚠</span><h2>常见农药毒性速查</h2></div>'+[{n:'百草枯',t:'剧毒',p:'禁止使用·无特效解毒药'},{n:'草甘膦',t:'低毒',p:'戴手套口罩·避免吸入'},{n:'敌敌畏',t:'高毒',p:'限制使用·全套防护'},{n:'乐果',t:'中毒',p:'戴防毒面具·橡胶手套'}].map(p=>`<div style="padding:8px;border-bottom:1px solid var(--border);font-size:15px"><strong>${p.n}</strong> · ${p.t} · ${p.p}</div>`).join('')+'</div>')}
_addPriceBoard(){const footer=document.querySelector('.app-footer');if(!footer)return;footer.insertAdjacentHTML('beforebegin','<div class="card" style="border-left:5px solid #0891b2"><div class="card-header"><span class="card-icon">📊</span><h2>工价行情参考（元/天）</h2></div>'+[{c:'小麦收割',p:'150-300'},{c:'水稻插秧',p:'120-250'},{c:'水果采摘',p:'100-200'},{c:'棉花采摘',p:'150-280'}].map(r=>`<div style="display:flex;justify-content:space-between;padding:6px 0;font-size:15px"><span>${r.c}</span><strong>${r.p}</strong></div>`).join('')+'<div style="font-size:12px;color:var(--text2);margin-top:4px">📌 价格随季节和地区变化。数据来源：农业用工市场。</div></div>')}
_addRatings(){const footer=document.querySelector('.app-footer');if(!footer)return;footer.insertAdjacentHTML('beforebegin','<div class="card" style="border-left:5px solid #f59e0b"><div class="card-header"><span class="card-icon">⭐</span><h2>雇主评价</h2></div><div id="ratingsLog"></div><button class="btn-secondary" id="btnAddRating">✏ 匿名评价</button></div>');document.getElementById('btnAddRating')?.addEventListener('click',()=>{const n=prompt('雇主/农场名称：');const s=prompt('评分(1-5)：');const c=prompt('评价：');if(n&&s){this.ratings.unshift({name:n,score:parseInt(s),comment:c||'',date:new Date().toISOString()});this._ss('gr_ratings',this.ratings.slice(-50));this._toast('✅ 已保存')}})}
_addSeasonal(){const footer=document.querySelector('.app-footer');if(!footer)return;const m=new Date().getMonth();const tips=m>=5&&m<=8?{icon:'🌡',t:'夏季防护',d:'防中暑+防蚊虫+多饮水+避开正午'}:(m>=10||m<=1)?{icon:'🥶',t:'冬季防护',d:'防冻伤+防滑倒+保暖+注意煤气'}:{icon:'🍂',t:'春秋防护',d:'花粉过敏+温差大+注意添减衣物'};footer.insertAdjacentHTML('beforebegin',`<div class="card" style="border-left:5px solid var(--primary)"><div class="card-header"><span class="card-icon">📅</span><h2>季节性健康提醒</h2></div><div style="font-size:16px"><strong>${tips.icon} ${tips.t}</strong><br>${tips.d}</div></div>`)}
_addBodyLog(){const footer=document.querySelector('.app-footer');if(!footer)return;footer.insertAdjacentHTML('beforebegin','<div class="card" style="border-left:5px solid var(--success)"><div class="card-header"><span class="card-icon">📝</span><h2>身体健康日志</h2></div><textarea id="bodyNote" rows="2" placeholder="今天身体感觉如何？" style="width:100%;padding:12px;border:2px solid var(--border);border-radius:10px;font-size:16px"></textarea><button class="btn-primary" id="btnSaveBody">保存</button></div>');document.getElementById('btnSaveBody')?.addEventListener('click',()=>{const t=document.getElementById('bodyNote').value.trim();if(t){this.bodyLog.unshift({date:new Date().toISOString(),text:t});this._ss('gr_body',this.bodyLog.slice(-100));this._toast('✅ 已保存')}})}
_addRegional(){const footer=document.querySelector('.app-footer');if(!footer)return;footer.insertAdjacentHTML('beforebegin','<div class="card" style="border-left:5px solid #7c3aed"><div class="card-header"><span class="card-icon">🗺</span><h2>跨区域务工信息</h2></div>'+[{r:'新疆',c:'棉花·9-10月',p:'¥200-350/天'},{r:'广西',c:'甘蔗·11-2月',p:'¥150-250/天'},{r:'河南',c:'小麦·5-6月',p:'¥150-300/天'},{r:'云南',c:'花卉·全年',p:'¥100-200/天'}].map(i=>`<div style="padding:6px 0;font-size:15px;border-bottom:1px solid var(--border)"><strong>${i.r}</strong> · ${i.c} · ${i.p}</div>`).join('')+'</div>')}
_addChildren(){const footer=document.querySelector('.app-footer');if(!footer)return;footer.insertAdjacentHTML('beforebegin','<div class="card" style="border-left:5px solid #db2777"><div class="card-header"><span class="card-icon">👶</span><h2>子女教育信息</h2></div><div style="font-size:15px;line-height:1.8">📌 随迁子女入学：需居住证+工作证明+户口本<br>📌 留守儿童关爱：联系当地民政部门或学校<br>📌 教育补贴：部分地区有农民工子女教育补贴<br>📞 咨询：当地教育局或12345市民热线</div></div>')}
_addReport(){const footer=document.querySelector('.app-footer');if(!footer)return;footer.insertAdjacentHTML('beforebegin','<button class="btn-secondary" id="btnExport">📊 导出工资+农药记录</button>');document.getElementById('btnExport')?.addEventListener('click',()=>{const report=PDFExporter.fullReport({title:'谷雨·工作记录',events:this.wages.slice(0,30)});PDFExporter.download(report,'谷雨-工作记录.txt');this._toast('✅ 已下载')})}
_renderAchievements(){const footer=document.querySelector('.app-footer');if(!footer)return;const ach=[];if(this.wages.length>=10)ach.push('💰 记录10笔工资');if(this.pesticides.length>=5)ach.push('🧪 农药监测');footer.insertAdjacentHTML('beforebegin',ach.length?`<div style="text-align:center;font-size:14px;padding:8px">🏆 ${ach.join(' · ')}</div>`:'')}
_toast(m,type='success'){const ex=document.querySelector('.toast');if(ex)ex.remove();const t=document.createElement('div');t.className=`toast ${type}`;t.textContent=m;document.body.appendChild(t);setTimeout(()=>t.remove(),2500)}
}
document.addEventListener('DOMContentLoaded',()=>new GrainRainV2());
