// 谷雨 · 农业工人
class GrainRainApp{constructor(){this.wages=this._load('gr_wages');this.pesticides=this._load('gr_pest');this.init()}
_load(k){try{return JSON.parse(localStorage.getItem(k)||'[]')}catch{return[]}}
_save(k,d){localStorage.setItem(k,JSON.stringify(d))}
init(){this._bind();this._renderWages();this._renderPesticides();this._renderHealthTips()}
_bind(){document.getElementById('btnSearchWork')?.addEventListener('click',()=>this._searchWork());document.getElementById('btnAddWage')?.addEventListener('click',()=>document.getElementById('wageModal').classList.remove('hidden'));document.getElementById('btnWageCancel')?.addEventListener('click',()=>document.getElementById('wageModal').classList.add('hidden'));document.getElementById('btnWageSave')?.addEventListener('click',()=>this._saveWage());document.getElementById('btnAddPesticide')?.addEventListener('click',()=>document.getElementById('pestModal').classList.remove('hidden'));document.getElementById('btnPestCancel')?.addEventListener('click',()=>document.getElementById('pestModal').classList.add('hidden'));document.getElementById('btnPestSave')?.addEventListener('click',()=>this._savePest());document.querySelectorAll('.modal-overlay').forEach(o=>o.addEventListener('click',e=>{if(e.target===o)o.classList.add('hidden')}))}
_searchWork(){const loc=document.getElementById('location').value.trim();const crop=document.getElementById('cropType').value;document.getElementById('workResults').innerHTML='<div style="padding:16px;text-align:center;background:var(--primary-bg);border-radius:10px;margin-top:12px"><strong>📋 农活信息</strong><br><span style="font-size:14px;color:var(--text2)">'+loc+'的'+(crop==='all'?'各类':document.getElementById('cropType').selectedOptions[0].text)+'农活信息需要接入本地农业用工平台。当前可手动记录已完成的农活和工资。</span></div>'}
_saveWage(){const emp=document.getElementById('wageEmployer').value.trim();const amt=parseFloat(document.getElementById('wageAmount').value)||0;const days=parseFloat(document.getElementById('wageDays').value)||0;if(!emp||!amt){this._toast('请填写雇主和金额','error');return}this.wages.unshift({date:new Date().toISOString(),employer:emp,amount:amt,days});this._save('gr_wages',this.wages.slice(-100));document.getElementById('wageModal').classList.add('hidden');document.getElementById('wageEmployer').value='';document.getElementById('wageAmount').value='0';this._renderWages();this._toast('✅ 工资已记录')}
_renderWages(){const now=new Date();const month=this.wages.filter(w=>{const d=new Date(w.date);return d.getMonth()===now.getMonth()});const total=month.reduce((s,w)=>s+w.amount,0);document.getElementById('wageBadge').textContent='本月¥'+total;const c=document.getElementById('wageLog');if(!this.wages.length){c.innerHTML='<div style="font-size:14px;color:var(--text2);text-align:center;padding:8px;">工资记录是追讨欠薪的重要证据</div>';return}c.innerHTML=this.wages.slice(0,10).map(w=>`<div class="wage-item"><span>${w.employer} · ${w.days}天</span><strong>¥${w.amount}</strong></div>`).join('')}
_savePest(){const name=document.getElementById('pestName').value.trim();const hours=parseFloat(document.getElementById('pestHours').value)||0;const prot=document.getElementById('pestProtection').value;if(!name){this._toast('请填写农药名称','error');return}this.pesticides.unshift({date:new Date().toISOString(),name,hours,protection:prot});this._save('gr_pest',this.pesticides.slice(-100));document.getElementById('pestModal').classList.add('hidden');document.getElementById('pestName').value='';this._renderPesticides();this._toast('✅ 已记录')}
_renderPesticides(){const c=document.getElementById('pesticideLog');const protLabels={none:'⚠ 无防护',mask:'口罩',full:'✅ 全套'};if(!this.pesticides.length){c.innerHTML='<div style="font-size:14px;color:var(--text2);text-align:center;padding:8px;">农药暴露记录是职业病认定的关键证据</div>';return}c.innerHTML=this.pesticides.slice(0,10).map(p=>`<div class="pest-item"><span>${p.name} · ${p.hours}h</span><span style="font-size:13px;color:${p.protection==='none'?'var(--danger)':'var(--success)'}">${protLabels[p.protection]}</span></div>`).join('');const hasRisk=this.pesticides.some(p=>p.protection==='none');document.getElementById('healthWarnings').innerHTML=hasRisk?'<div class="health-warning">⚠ 检测到无防护农药接触！农药可经皮肤和呼吸道吸收。务必佩戴手套和口罩。每年做一次肝功能检查。</div>':''}
_renderHealthTips(){const tips=[{icon:'🌡',t:'中暑预防',d:'气温>35°C时避免11:00-15:00田间作业。每小时饮水500ml。'},{icon:'🤧',t:'农药中毒症状',d:'头晕、恶心、皮肤刺痛、视力模糊。立即离开施药区域，清水冲洗接触部位。'},{icon:'🏥',t:'职业病认定',d:'农药中毒属于职业病。保留接触记录和医疗证明，可申请工伤认定。'}];document.getElementById('healthTips').innerHTML=tips.map(t=>`<div class="health-warning" style="background:var(--bg);border:1px solid var(--border);margin-top:6px"><strong>${t.icon} ${t.t}</strong><br><span style="font-size:14px">${t.d}</span></div>`).join('')}
_toast(msg,type='success'){const ex=document.querySelector('.toast');if(ex)ex.remove();const t=document.createElement('div');t.className=`toast ${type}`;t.textContent=msg;document.body.appendChild(t);setTimeout(()=>t.remove(),2500)}}
document.addEventListener('DOMContentLoaded',()=>new GrainRainApp());
