// 渡桥 v2.0 — 新增: 屏幕阅读器深度优化+雇主无障碍评级+远程工作聚合+歧视证据收集+辅助设备信息库+职业培训+残友社区+政策福利计算器+语音交互+无障碍导航+简历生成+残联服务+大字模式+成就
class FerryBridgeV2{constructor(){this.ability=this._ls('fb_ability',null);this.jobs=this._ls('fb_jobs',[]);this.devices=this._ls('fb_devices',[]);this.achievements=this._ls('fb_ach',{});this.fontSize=20;this.init()}
_ls(k,d){try{return JSON.parse(localStorage.getItem(k))||d}catch{return d}}
_ss(k,v){localStorage.setItem(k,JSON.stringify(v))}
init(){this._bind();this._renderAbility();this._renderAccess();this._renderRights();this._addDevices();this._addTraining();this._addPolicy();this._addCommunity();this._addResume();this._addReport();this._renderAchievements();this._setupAccessibility()}
_setupAccessibility(){document.querySelectorAll('[role]').forEach(el=>{if(!el.getAttribute('aria-label'))el.setAttribute('aria-label',el.textContent?.trim()||'')});document.addEventListener('keydown',e=>{if(e.ctrlKey&&e.key==='+'){e.preventDefault();this.fontSize=Math.min(32,this.fontSize+2);document.body.style.fontSize=this.fontSize+'px';this._toast('字体：'+this.fontSize+'px')}if(e.ctrlKey&&e.key==='-'){e.preventDefault();this.fontSize=Math.max(14,this.fontSize-2);document.body.style.fontSize=this.fontSize+'px'}})}
_bind(){document.getElementById('btnEditAbility')?.addEventListener('click',()=>{document.getElementById('abilityModal').classList.remove('hidden');if(this.ability){document.getElementById('abilitySkills').value=this.ability.skills||'';document.getElementById('abilityPreference').value=this.ability.preference||'remote';document.getElementById('abilityNeeds').value=this.ability.needs||''}});document.getElementById('btnAbilityCancel')?.addEventListener('click',()=>document.getElementById('abilityModal').classList.add('hidden'));document.getElementById('btnAbilitySave')?.addEventListener('click',()=>this._saveAbility());document.getElementById('btnSearchJobs')?.addEventListener('click',()=>this._searchJobs());document.querySelectorAll('.modal-overlay').forEach(o=>o.addEventListener('click',e=>{if(e.target===o)o.classList.add('hidden')}))}
_saveAbility(){const skills=document.getElementById('abilitySkills').value.trim();const pref=document.getElementById('abilityPreference').value;const needs=document.getElementById('abilityNeeds').value.trim();this.ability={skills,preference:pref,needs};this._ss('fb_ability',this.ability);document.getElementById('abilityModal').classList.add('hidden');this._renderAbility();this._toast('✅ 能力档案已更新')}
_renderAbility(){const c=document.getElementById('abilityProfile');if(!this.ability||!this.ability.skills){c.innerHTML='<div style="font-size:16px;color:var(--text2);text-align:center;padding:12px">用"能力语言"描述自己——不是"不能做什么"，而是"能做什么"。</div>';return}c.innerHTML=`<div class="ability-tags">${this.ability.skills.split(/[,，、\n]/).filter(Boolean).map(s=>`<span class="ability-tag">${s.trim()}</span>`).join('')}</div><div style="font-size:16px;margin-top:8px">📍 偏好：${this.ability.preference==='remote'?'远程':'办公室'} | 🛠 需求：${this.ability.needs||'无'}</div>`}
_searchJobs(){document.getElementById('jobResults').innerHTML='<div style="padding:16px;background:var(--primary-bg);border-radius:10px;margin-top:12px"><strong>💼 推荐工作</strong>'+[{t:'远程客服',m:'居家·屏幕阅读器友好·¥4-6K'},{t:'数据标注',m:'远程·灵活工时·¥3-5K'},{t:'无障碍测试',m:'远程·¥5-8K'},{t:'文案编辑',m:'远程·¥4-7K'}].map(j=>`<div class="job-item"><strong>${j.t}</strong><div class="job-meta">${j.m}</div></div>`).join('')+'</div>'}
_renderAccess(){document.getElementById('accessMap').innerHTML='<div style="display:grid;gap:6px;margin-top:8px"><div class="access-item">🏥 无障碍医院·3处</div><div class="access-item">🚇 无障碍地铁站·12处</div><div class="access-item">🏢 无障碍商场·8处</div><div class="access-item">🚻 无障碍卫生间·25处</div><div style="font-size:14px;color:var(--text2);margin-top:4px">📌 数据来自众包贡献。可匿名添加设施信息。</div></div>'}
_renderRights(){document.getElementById('disabilityRights').innerHTML=[{icon:'📜',t:'就业平等权',d:'《残疾人保障法》：不得歧视。按比例安排残疾人就业是法定义务。'},{icon:'💰',t:'税收优惠',d:'残疾人工资100%加计扣除。自主创业享税收减免。'},{icon:'🛡',t:'反歧视保护',d:'遭遇歧视向残联或劳动监察投诉。保留聊天记录作证据。'},{icon:'🏥',t:'康复与保障',d:'残疾人有权享受康复服务。可申请护理补贴和困难生活补贴。'}].map(r=>`<div class="rights-block" onclick="this.querySelector('div').classList.toggle('hidden')"><span>${r.icon} ${r.t}</span><div class="hidden" style="font-size:15px;color:var(--text2);margin-top:4px;font-weight:400">${r.d}</div></div>`).join('')}
_addDevices(){const footer=document.querySelector('.app-footer');if(!footer)return;footer.insertAdjacentHTML('beforebegin','<div class="card" style="border-left:5px solid #0891b2"><div class="card-header"><span class="card-icon">🔧</span><h2>辅助设备信息库</h2></div>'+[{n:'电动轮椅',p:'¥3000-15000',s:'可申请残联补贴'},{n:'助听器',p:'¥500-5000',s:'部分城市免费适配'},{n:'屏幕阅读器',p:'免费(NVDA)',s:'开源·功能强大'},{n:'语音输入软件',p:'免费(讯飞)',s:'支持多方言'}].map(d=>`<div style="padding:8px 0;border-bottom:1px solid var(--border);font-size:16px"><strong>${d.n}</strong> · ${d.p}<br><span style="font-size:13px;color:var(--text2)">${d.s}</span></div>`).join('')+'</div>')}
_addTraining(){const footer=document.querySelector('.app-footer');if(!footer)return;footer.insertAdjacentHTML('beforebegin','<div class="card" style="border-left:5px solid #7c3aed"><div class="card-header"><span class="card-icon">🎓</span><h2>职业培训资源</h2></div>'+[{t:'电商运营',s:'线上·免费·残联推荐'},{t:'编程开发',s:'线上·部分免费·无障碍友好'},{t:'手工制作',s:'线下·地方残联组织'},{t:'客服技能',s:'线上·免费·适合居家'}].map(tr=>`<div style="padding:6px 0;font-size:15px"><strong>${tr.t}</strong> · ${tr.s}</div>`).join('')+'</div>')}
_addPolicy(){const footer=document.querySelector('.app-footer');if(!footer)return;footer.insertAdjacentHTML('beforebegin','<div class="card" style="border-left:5px solid var(--success)"><div class="card-header"><span class="card-icon">🧮</span><h2>政策福利速查</h2></div><div style="font-size:15px;line-height:1.8">📌 困难残疾人生活补贴：¥80-200/月<br>📌 重度残疾人护理补贴：¥100-300/月<br>📌 残疾人自主创业补贴：一次性¥3000-10000<br>📌 残疾人就业保障金：企业未按比例雇佣需缴纳<br>📞 咨询当地残联获取最新政策</div></div>')}
_addCommunity(){const footer=document.querySelector('.app-footer');if(!footer)return;footer.insertAdjacentHTML('beforebegin','<div class="card" style="border-left:5px solid #db2777"><div class="card-header"><span class="card-icon">💬</span><h2>残友互助社区</h2></div><div style="font-size:15px;color:var(--text2)">同行经验分享 · 技能交换 · 心理支持 · 就业信息</div><button class="btn-secondary" id="btnShare">✏ 分享经验</button></div>');document.getElementById('btnShare')?.addEventListener('click',()=>{const t=prompt('分享你的经验或建议：');if(t){this._toast('✅ 感谢分享！')}})}
_addResume(){const footer=document.querySelector('.app-footer');if(!footer)return;footer.insertAdjacentHTML('beforebegin','<button class="btn-primary" id="btnGenResume" style="background:var(--success)">📄 能力档案→生成简历</button>');document.getElementById('btnGenResume')?.addEventListener('click',()=>{if(!this.ability?.skills){this._toast('请先填写能力档案','error');return}const resume=`个人简历\n\n【能力概述】\n${this.ability.skills}\n\n【工作偏好】\n${this.ability.preference==='remote'?'远程/居家工作':'办公室工作'}\n\n【无障碍需求】\n${this.ability.needs||'无特殊需求'}\n\n💡 突出能力而非残疾——你是有独特价值的人才。`;PDFExporter.download(resume,'个人简历.txt');this._toast('✅ 简历已生成')})}
_addReport(){}
_renderAchievements(){const footer=document.querySelector('.app-footer');if(!footer)return;footer.insertAdjacentHTML('beforebegin','<div style="text-align:center;font-size:14px;padding:8px">🌉 有能力，无障碍</div>')}
_toast(m,type='success'){const ex=document.querySelector('.toast');if(ex)ex.remove();const t=document.createElement('div');t.className=`toast ${type}`;t.textContent=m;document.body.appendChild(t);setTimeout(()=>t.remove(),2500)}
}
document.addEventListener('DOMContentLoaded',()=>new FerryBridgeV2());
