// 渡桥 · 残疾人劳动者
class FerryBridgeApp{constructor(){this.ability=this._load('fb_ability');this.init()}
_load(k){try{return JSON.parse(localStorage.getItem(k))}catch{return null}}
_save(k,d){localStorage.setItem(k,JSON.stringify(d))}
init(){this._bind();this._renderAbility();this._renderAccess();this._renderRights()}
_bind(){document.getElementById('btnEditAbility')?.addEventListener('click',()=>{document.getElementById('abilityModal').classList.remove('hidden');if(this.ability){document.getElementById('abilitySkills').value=this.ability.skills||'';document.getElementById('abilityPreference').value=this.ability.preference||'remote';document.getElementById('abilityNeeds').value=this.ability.needs||''}});document.getElementById('btnAbilityCancel')?.addEventListener('click',()=>document.getElementById('abilityModal').classList.add('hidden'));document.getElementById('btnAbilitySave')?.addEventListener('click',()=>this._saveAbility());document.getElementById('btnSearchJobs')?.addEventListener('click',()=>this._searchJobs());document.querySelectorAll('.modal-overlay').forEach(o=>o.addEventListener('click',e=>{if(e.target===o)o.classList.add('hidden')}))}
_saveAbility(){const skills=document.getElementById('abilitySkills').value.trim();const pref=document.getElementById('abilityPreference').value;const needs=document.getElementById('abilityNeeds').value.trim();this.ability={skills,preference:pref,needs};this._save('fb_ability',this.ability);document.getElementById('abilityModal').classList.add('hidden');this._renderAbility();this._toast('✅ 能力档案已更新')}
_renderAbility(){const c=document.getElementById('abilityProfile');if(!this.ability||!this.ability.skills){c.innerHTML='<div style="font-size:16px;color:var(--text2);text-align:center;padding:12px;">还没有能力档案。点击下方按钮，用"能力语言"描述你自己——不是"不能做什么"，而是"能做什么"。</div>';return}c.innerHTML=`<div class="ability-tags">${this.ability.skills.split(/[,，、\n]/).filter(Boolean).map(s=>`<span class="ability-tag">${s.trim()}</span>`).join('')}</div><div style="font-size:16px;margin-top:8px">📍 偏好：${this.ability.preference==='remote'?'远程/居家':'办公室'} | 🛠 无障碍需求：${this.ability.needs||'无特殊需求'}</div>`}
_searchJobs(){const skills=this.ability?.skills||'';document.getElementById('jobResults').innerHTML=`<div style="padding:16px;background:var(--primary-bg);border-radius:10px;margin-top:12px"><strong>💼 工作匹配</strong><br><span style="font-size:15px;color:var(--text2)">基于你的能力档案${skills?'（'+skills.split(/[,，]/)[0]+'等）':''}：</span><div class="job-item"><strong>远程客服</strong><div class="job-meta">居家 · 屏幕阅读器友好 · ¥4000-6000</div></div><div class="job-item"><strong>数据标注员</strong><div class="job-meta">远程 · 灵活工时 · ¥3000-5000</div></div><div class="job-item"><strong>无障碍测试员</strong><div class="job-meta">远程/混合 · 需要无障碍体验 · ¥5000-8000</div></div><div style="font-size:14px;color:var(--text2);margin-top:8px">📌 以上为示例匹配。接入真实招聘平台后可获得完整结果。</div></div>`}
_renderAccess(){document.getElementById('accessMap').innerHTML='<div style="display:grid;gap:6px;margin-top:8px"><div class="access-item">🏥 无障碍医院 · 3处</div><div class="access-item">🚇 无障碍地铁站 · 12处</div><div class="access-item">🏢 无障碍商场 · 8处</div><div class="access-item">🚻 无障碍卫生间 · 25处</div><div style="font-size:14px;color:var(--text2);margin-top:4px">📌 数据来自众包贡献。接入地图API后可获取实时数据。</div></div>'}
_renderRights(){const rights=[{icon:'📜',t:'就业平等权',d:'《残疾人保障法》规定：用人单位不得歧视残疾人。按比例安排残疾人就业是法定义务。'},{icon:'💰',t:'税收优惠',d:'残疾人工资可100%加计扣除。自主创业可享受税收减免和小额贷款支持。'},{icon:'🛡',t:'反歧视保护',d:'遭遇就业歧视可向残联或劳动监察部门投诉。保留招聘过程中的聊天记录和邮件作为证据。'},{icon:'🏥',t:'康复与保障',d:'残疾人有权享受康复服务。重度残疾人可申请护理补贴。低保残疾人可申请困难残疾人生活补贴。'}];document.getElementById('disabilityRights').innerHTML=rights.map(r=>`<div class="rights-block" onclick="this.querySelector('div').classList.toggle('hidden')"><span>${r.icon} ${r.t}</span><div class="hidden" style="font-size:15px;color:var(--text2);margin-top:4px;font-weight:400">${r.d}</div></div>`).join('')}
_toast(msg,type='success'){const ex=document.querySelector('.toast');if(ex)ex.remove();const t=document.createElement('div');t.className=`toast ${type}`;t.textContent=msg;document.body.appendChild(t);setTimeout(()=>t.remove(),2500)}}
document.addEventListener('DOMContentLoaded',()=>new FerryBridgeApp());
