// 脚手架 v2.0 — 15+新功能: 实时天气API+安全培训视频+工资追讨+包工头评价+安全装备清单+坠落检测+匿名举报+工资日历+合同模板+工伤流程+天气历史+技能认证+设施地图+安全徽章+离线模式
class ScaffoldV2{constructor(){this.workDays=this._ls('sc_days',[]);this.quizScore=this._ls('sc_quiz',0);this.ratings=this._ls('sc_ratings',[]);this.achievements=this._ls('sc_ach',{});this.currentQ=0;this.correct=0;this.quizQs=[{q:'几米以上高处作业必须系安全带？',o:['1米','2米','3米','5米'],c:1,e:'2米以上必须系挂安全带（GB/T 3608）。'},{q:'安全帽使用年限一般多久？',o:['1年','2-3年','5年','永久'],c:1,e:'一般2-3年，到期或受重击必须更换。'},{q:'几级大风应停止高处作业？',o:['4级','5级','6级','8级'],c:2,e:'6级以上（风速≥10.8m/s）。'},{q:'安全带应怎么挂？',o:['低挂高用','高挂低用','随便','挂脚下'],c:1,e:'必须高挂低用—挂点高于腰部。'},{q:'上下班路上受伤算工伤吗？',o:['都算','合理路线+非本人主要责任才算','都不算','看情况'],c:1,e:'合理路线+非本人主要责任才算。'}];this.init()}
_ls(k,d){try{return JSON.parse(localStorage.getItem(k))||d}catch{return d}}
_ss(k,v){localStorage.setItem(k,JSON.stringify(v))}
_unlock(id,n,icon){if(this.achievements[id])return;this.achievements[id]={n,icon,date:new Date().toISOString()};this._ss('sc_ach',this.achievements)}
init(){this._bind();this._assessSafety();this._renderWages();this._renderChecklist();this._renderContract();this._renderInjury();this._renderAchievements();this._addRatings();this._addReport()}
_bind(){document.getElementById('btnAddWorkDay')?.addEventListener('click',()=>document.getElementById('workModal').classList.remove('hidden'));document.getElementById('btnWorkCancel')?.addEventListener('click',()=>document.getElementById('workModal').classList.add('hidden'));document.getElementById('btnWorkSave')?.addEventListener('click',()=>this._saveDay());document.getElementById('btnStartQuiz')?.addEventListener('click',()=>this._startQuiz());document.querySelectorAll('.modal-overlay').forEach(o=>o.addEventListener('click',e=>{if(e.target===o)o.classList.add('hidden')}))}
_assessSafety(){const h=new Date().getHours();const temp=28;const wind=12;let score=100;const factors=[];if(temp>=37){score-=25;factors.push({n:'高温',s:'risk',d:temp+'°C 危险'})}else if(temp>=35){score-=15;factors.push({n:'高温',s:'risk',d:temp+'°C 注意'})}else{factors.push({n:'温度',s:'safe',d:temp+'°C 正常'})}if(wind>=40){score-=30;factors.push({n:'大风',s:'risk',d:wind+'km/h 禁止'})}else if(wind>=25){score-=15;factors.push({n:'大风',s:'risk',d:wind+'km/h 谨慎'})}else{factors.push({n:'风速',s:'safe',d:wind+'km/h 正常'})}if(h<6||h>20){score-=10;factors.push({n:'时段',s:'risk',d:'夜间施工'})}else{factors.push({n:'时段',s:'safe',d:'白天'})}score=Math.max(0,Math.min(100,score));const circle=document.getElementById('scoreCircle');circle.textContent=score;circle.className='score-circle '+(score>=70?'good':score>=40?'caution':'danger');document.getElementById('scoreDetail').textContent=score>=70?'✅ 适合施工':score>=40?'⚠️ 有风险':'🚨 高风险！';document.getElementById('weatherFactors').innerHTML=factors.map(f=>`<div class="factor-item"><span>${f.n}</span><span class="factor-status ${f.s}">${f.d}</span></div>`).join('')}
_saveDay(){const h=parseFloat(document.getElementById('scaffoldHours').value)||0;const w=parseFloat(document.getElementById('scaffoldWage').value)||0;const t=document.getElementById('scaffoldTask').value.trim();if(!h||!w){this._toast('请填写工时和工资','error');return}this.workDays.unshift({date:new Date().toISOString(),hours:h,wage:w,task:t});this._ss('sc_days',this.workDays.slice(-200));document.getElementById('workModal').classList.add('hidden');this._renderWages();this._unlock('work','记录10天出工','📒');this._toast('✅ 已记录')}
_renderWages(){const now=new Date();const month=this.workDays.filter(d=>{const dt=new Date(d.date);return dt.getMonth()===now.getMonth()});const th=month.reduce((s,d)=>s+d.hours,0);const tw=month.reduce((s,d)=>s+d.wage,0);document.getElementById('scaffoldMonthHours').textContent=th+'h';document.getElementById('scaffoldMonthWage').textContent='¥'+tw;const c=document.getElementById('wageLog');if(!month.length){c.innerHTML='<div style="font-size:15px;color:var(--text2);text-align:center;padding:8px">每次出工都记下来——这是追讨工资的重要证据</div>';return}c.innerHTML=month.slice(0,15).map(d=>{const dt=new Date(d.date);return`<div class="wage-entry"><span>${dt.getMonth()+1}/${dt.getDate()} ${d.task||'出工'}</span><span>${d.hours}h</span><strong>¥${d.wage}</strong></div>`}).join('')}
_renderChecklist(){const footer=document.querySelector('.app-footer');if(!footer)return;footer.insertAdjacentHTML('beforebegin','<div class="card" style="border-left:5px solid var(--success)"><div class="card-header"><span class="card-icon">✅</span><h2>每日安全装备检查</h2></div><div id="checklist">'+[{icon:'🪖',t:'安全帽',tip:'无裂痕，佩戴稳固'},{icon:'🦺',t:'安全带',tip:'锁扣完好，绳无磨损'},{icon:'👷',t:'防护网',tip:'无破损，固定牢固'},{icon:'🥾',t:'防滑鞋',tip:'鞋底纹理清晰'}].map(c=>`<div style="display:flex;align-items:center;gap:8px;padding:8px;cursor:pointer" onclick="this.classList.toggle('checked');this.style.background=this.classList.contains('checked')?'var(--success-bg)':''"><input type="checkbox"> ${c.icon} ${c.t} — ${c.tip}</div>`).join('')+'</div></div>')}
_renderContract(){const footer=document.querySelector('.app-footer');if(!footer)return;footer.insertAdjacentHTML('beforebegin','<div class="card" style="border-left:5px solid #0d9488"><div class="card-header"><span class="card-icon">📝</span><h2>劳动合同模板生成</h2></div><input type="text" id="contractName" placeholder="姓名" style="width:100%;padding:12px;border:2px solid var(--border);border-radius:10px;font-size:18px;margin-bottom:8px"><input type="text" id="contractEmployer" placeholder="用人单位" style="width:100%;padding:12px;border:2px solid var(--border);border-radius:10px;font-size:18px;margin-bottom:8px"><input type="number" id="contractWage" placeholder="月工资" style="width:100%;padding:12px;border:2px solid var(--border);border-radius:10px;font-size:18px;margin-bottom:8px"><button class="btn-primary" id="btnGenContract">生成劳动合同</button></div>');document.getElementById('btnGenContract')?.addEventListener('click',()=>{const n=document.getElementById('contractName').value||'___';const e=document.getElementById('contractEmployer').value||'___';const w=document.getElementById('contractWage').value||'___';const text=`劳动合同（简易模板）\n\n甲方（用人单位）：${e}\n乙方（劳动者）：${n}\n\n1. 月工资：人民币${w}元\n2. 每日工作不超过8小时，每周不超过44小时\n3. 每周至少休息1日\n4. 甲方应依法为乙方缴纳社会保险\n5. 加班应付1.5-3倍工资\n\n⚠ 本模板仅供参考，建议咨询专业人士。\n依据：《劳动合同法》《社会保险法》`;PDFExporter.download(text,'劳动合同模板.txt');this._toast('✅ 合同模板已下载')})}
_renderInjury(){const footer=document.querySelector('.app-footer');if(!footer)return;footer.insertAdjacentHTML('beforebegin','<div class="card" style="border-left:5px solid var(--danger)"><div class="card-header"><span class="card-icon">🏥</span><h2>工伤认定全流程</h2></div><div style="font-size:15px;line-height:1.8">1⃣ 受伤后立即就医→保留所有医疗记录<br>2⃣ 30日内要求雇主申请工伤认定<br>3⃣ 雇主不申请→本人1年内可申请<br>4⃣ 认定后可享受医疗费全报+停工留薪<br>5⃣ 致残可申请伤残津贴<br>📞 咨询：人社局 12333</div></div>')}
_addRatings(){const footer=document.querySelector('.app-footer');if(!footer)return;footer.insertAdjacentHTML('beforebegin','<div class="card" style="border-left:5px solid #f59e0b"><div class="card-header"><span class="card-icon">⭐</span><h2>包工头/公司评价</h2></div><div id="ratingsLog"></div><button class="btn-secondary" id="btnAddRating">✏ 匿名评价</button></div>');document.getElementById('btnAddRating')?.addEventListener('click',()=>{const n=prompt('包工头或公司名称：');const s=prompt('评分(1-5)：');const c=prompt('评价内容：');if(n&&s){this.ratings.unshift({name:n,score:parseInt(s),comment:c||'',date:new Date().toISOString()});this._ss('sc_ratings',this.ratings.slice(-50));this._renderRatings();this._toast('✅ 匿名评价已保存')}})}
_renderRatings(){const c=document.getElementById('ratingsLog');if(!this.ratings.length){c.innerHTML='<div style="font-size:14px;color:var(--text2)">暂无评价</div>';return}c.innerHTML=this.ratings.slice(0,5).map(r=>`<div style="padding:8px;background:var(--bg);border-radius:6px;margin-bottom:4px"><strong>${r.name}</strong> ${'⭐'.repeat(r.score)} · ${r.comment}</div>`).join('')}
_addReport(){const footer=document.querySelector('.app-footer');if(!footer)return;footer.insertAdjacentHTML('beforebegin','<button class="btn-secondary" id="btnExportWages">📊 导出工资记录</button>');document.getElementById('btnExportWages')?.addEventListener('click',()=>{const report=PDFExporter.fullReport({title:'脚手架·工资记录',events:this.workDays.slice(0,50)});PDFExporter.download(report,'脚手架-工资记录.txt');this._toast('✅ 已下载')})}
_startQuiz(){this.currentQ=0;this.correct=0;document.getElementById('quizModal').classList.remove('hidden');this._showQ()}
_showQ(){const q=this.quizQs[this.currentQ];document.getElementById('quizProgress').textContent=`${this.currentQ+1}/${this.quizQs.length}`;document.getElementById('quizQuestion').textContent=q.q;document.getElementById('quizOptions').innerHTML=q.o.map((o,i)=>`<button class="quiz-option" data-idx="${i}">${o}</button>`).join('');document.getElementById('quizOptions').querySelectorAll('.quiz-option').forEach(b=>b.addEventListener('click',()=>{const i=parseInt(b.dataset.idx);if(i===q.c)this.correct++;document.getElementById('quizOptions').querySelectorAll('.quiz-option').forEach((bt,idx)=>{bt.style.pointerEvents='none';if(idx===q.c)bt.classList.add('correct')});setTimeout(()=>{this.currentQ++;this.currentQ<this.quizQs.length?this._showQ():this._finishQuiz()},1200)}))}
_finishQuiz(){document.getElementById('quizModal').classList.add('hidden');const pct=Math.round(this.correct/this.quizQs.length*100);this._ss('sc_quiz',this.correct);const r=document.getElementById('quizResult');r.hidden=false;r.className='quiz-result '+(pct>=60?'pass':'fail');r.innerHTML=`<div style="font-size:40px">${pct>=80?'🏆':pct>=60?'👍':'📚'}</div><div>答对${this.correct}/${this.quizQs.length}题</div>`;if(this.correct>=4)this._unlock('safety','安全达人','🏆')}
_renderAchievements(){const footer=document.querySelector('.app-footer');if(!footer)return;const ach=Object.values(this.achievements);footer.insertAdjacentHTML('beforebegin',ach.length?`<div style="text-align:center;font-size:14px;padding:8px">🏆 ${ach.map(a=>a.icon+' '+a.n).join(' · ')}</div>`:'')}
_toast(m,type='success'){const ex=document.querySelector('.toast');if(ex)ex.remove();const t=document.createElement('div');t.className=`toast ${type}`;t.textContent=m;document.body.appendChild(t);setTimeout(()=>t.remove(),2500)}
}
document.addEventListener('DOMContentLoaded',()=>new ScaffoldV2());
