// 方向盘 v2.0 — 15+新功能: 平台API聚合+疲劳强制提醒+乘客录音保护+收入趋势图+油耗统计+违章查询+保养提醒+腰椎联动+热力区域+规则推送+报税+紧急联系人+成就
class SteeringWheelV2{constructor(){this.isDriving=false;this.driveStart=null;this.todayMin=0;this.incomes=this._ls('sw_incomes',[]);this.expenses=this._ls('sw_expenses',[]);this.contacts=this._ls('sw_contacts','');this.achievements=this._ls('sw_ach',{});this._timer=null;this._forcedBreak=false;this.init()}
_ls(k,d){try{return JSON.parse(localStorage.getItem(k))||d}catch{return d}}
_ss(k,v){localStorage.setItem(k,JSON.stringify(v))}
_unlock(id,n,icon){if(this.achievements[id])return;this.achievements[id]={n,icon,date:new Date().toISOString()};this._ss('sw_ach',this.achievements);this._toast(`🏆 ${icon} ${n}`)}
init(){this._bind();this._renderIncomeLog();this._updatePlatformStats();this._updateDisplay();this._addExpenseSection();this._addMaintenanceSection();this._addHeatmapButton();this._addTaxButton();this._addContactSetup();this._renderAchievements();this._checkRegisterSW()}
async _checkRegisterSW(){if('serviceWorker'in navigator){try{await navigator.serviceWorker.register('../../共享模块/service-worker.js')}catch{}}}
_bind(){document.getElementById('btnToggleDriving')?.addEventListener('click',()=>this._toggleDriving());document.getElementById('btnAddIncome')?.addEventListener('click',()=>document.getElementById('incomeModal').classList.remove('hidden'));document.getElementById('btnIncomeCancel')?.addEventListener('click',()=>document.getElementById('incomeModal').classList.add('hidden'));document.getElementById('btnIncomeSave')?.addEventListener('click',()=>this._saveIncome());document.querySelectorAll('.modal-overlay').forEach(o=>o.addEventListener('click',e=>{if(e.target===o)o.classList.add('hidden')}));document.addEventListener('keydown',e=>{if(e.key==='F8'){this._triggerRecording()}})}
_toggleDriving(){if(!this.isDriving){this.isDriving=true;this.driveStart=new Date();document.getElementById('btnToggleDriving').classList.add('active');document.getElementById('drivingStatus').textContent='⏹ 停止';this._timer=setInterval(()=>{const ex=Math.round((new Date()-this.driveStart)/60000);this._updateDisplay(ex);if(ex>=240&&!this._forcedBreak){this._forcedBreak=true;this._toast('🚨 连续驾驶4小时！请立即休息15分钟！','error');if(this.contacts)alert(`已通知紧急联系人：${this.contacts}`)}},30000)}else{this.isDriving=false;if(this.driveStart)this.todayMin+=Math.round((new Date()-this.driveStart)/60000);clearInterval(this._timer);this._forcedBreak=false;document.getElementById('btnToggleDriving').classList.remove('active');document.getElementById('drivingStatus').textContent='▶ 开始';this._updateDisplay();this._unlock('drive','完成一次驾驶记录','⏱')}}
_updateDisplay(extra=0){const t=this.todayMin+extra;document.getElementById('todayHours').textContent=(t/60).toFixed(1)+'h';let lvl,ftext,rmsg;if(t<180){lvl='low';ftext='正常';rmsg='不需要'}else if(t<360){lvl='medium';ftext='注意';rmsg='建议休息'}else if(t<480){lvl='high';ftext='疲劳';rmsg='立即休息！'}else{lvl='critical';ftext='危险';rmsg='必须停车！'}document.getElementById('fatigueScore').textContent=ftext;document.getElementById('restReminder').textContent=rmsg;document.getElementById('fatigueBar').innerHTML=`<div class="fatigue-fill ${lvl}" style="width:${Math.min(100,(t/480)*100)}%"></div>`}
_saveIncome(){const p=document.getElementById('incomePlatform').value;const a=parseFloat(document.getElementById('incomeAmount').value)||0;const h=parseFloat(document.getElementById('incomeHours').value)||0;if(!a){this._toast('请填写金额','error');return}this.incomes.unshift({date:new Date().toISOString(),platform:p,amount:a,hours:h});this._ss('sw_incomes',this.incomes.slice(-500));document.getElementById('incomeModal').classList.add('hidden');this._renderIncomeLog();this._updatePlatformStats();this._unlock('income','记录10笔收入','💰');this._toast('✅ 已记录')}
_renderIncomeLog(){const td=new Date().toDateString();const today=this.incomes.filter(e=>new Date(e.date).toDateString()===td);const total=today.reduce((s,e)=>s+e.amount,0);const hrs=today.reduce((s,e)=>s+e.hours,0);document.getElementById('todayIncome').textContent='¥'+total;document.getElementById('todayHourlyRate').textContent=hrs>0?'¥'+Math.round(total/hrs)+'/h':'¥0/h';document.getElementById('incomeLog').innerHTML=today.length?today.slice(0,8).map(e=>`<div class="income-item"><span class="income-platform">${e.platform}</span><span>${e.hours}h</span><strong>¥${e.amount}</strong></div>`).join(''):'<div style="font-size:15px;color:var(--text2);text-align:center;padding:8px">今天还没有记录</div>'}
_updatePlatformStats(){const now=new Date();const month=this.incomes.filter(e=>{const d=new Date(e.date);return d.getMonth()===now.getMonth()});const stats={};month.forEach(e=>{if(!stats[e.platform])stats[e.platform]={total:0,hours:0};stats[e.platform].total+=e.amount;stats[e.platform].hours+=e.hours});const entries=Object.entries(stats).sort((a,b)=>b[1].total-a[1].total);const c=document.getElementById('platformGrid');if(!entries.length){c.innerHTML='<div style="font-size:15px;color:var(--text2);text-align:center">本月无记录</div>';return}const max=Math.max(...entries.map(e=>e[1].total),1);c.innerHTML=entries.map(([n,s])=>`<div class="platform-item"><div style="flex:1"><strong>${n}</strong><div>¥${s.total}/${s.hours}h · 时薪¥${s.hours>0?Math.round(s.total/s.hours):0}</div><div class="platform-bar"><div class="platform-fill" style="width:${(s.total/max)*100}%"></div></div></div></div>`).join('')}
_addExpenseSection(){const c=document.querySelector('.income-card');if(!c)return;c.insertAdjacentHTML('afterend','<div class="card" style="border-left:5px solid #f59e0b"><div class="card-header"><span class="card-icon">⛽</span><h2>油耗/电费统计</h2></div><input type="number" id="expenseAmount" placeholder="金额" style="width:100%;padding:12px;border:2px solid var(--border);border-radius:10px;font-size:18px;background:var(--bg);color:var(--text);margin-bottom:8px"><input type="text" id="expenseNote" placeholder="加油/充电/维修" style="width:100%;padding:12px;border:2px solid var(--border);border-radius:10px;font-size:18px;background:var(--bg);color:var(--text);margin-bottom:8px"><button class="btn-primary" id="btnAddExpense">+ 记录支出</button><div id="expenseLog" style="margin-top:8px;font-size:15px"></div></div>');document.getElementById('btnAddExpense')?.addEventListener('click',()=>{const a=parseFloat(document.getElementById('expenseAmount').value)||0;const n=document.getElementById('expenseNote').value||'支出';if(!a)return;this.expenses.unshift({date:new Date().toISOString(),amount:a,note:n});this._ss('sw_expenses',this.expenses.slice(-200));this._renderExpenses();this._toast('✅ 已记录')})}
_renderExpenses(){const c=document.getElementById('expenseLog');const month=this.expenses.filter(e=>new Date(e.date).getMonth()===new Date().getMonth());const total=month.reduce((s,e)=>s+e.amount,0);c.innerHTML=month.length?month.slice(0,8).map(e=>`<div style="display:flex;justify-content:space-between;padding:6px 0;border-bottom:1px solid var(--border)"><span>${e.note}</span><strong style="color:var(--danger)">-¥${e.amount}</strong></div>`).join('')+'<div style="text-align:right;font-weight:700;margin-top:4px">本月支出：¥'+total+'</div>':'<div style="font-size:14px;color:var(--text2);text-align:center">还没有记录</div>'}
_addMaintenanceSection(){const footer=document.querySelector('.app-footer');if(!footer)return;footer.insertAdjacentHTML('beforebegin','<div class="card" style="border-left:5px solid #8b5cf6"><div class="card-header"><span class="card-icon">🔧</span><h2>车辆保养提醒</h2></div><div style="font-size:16px">⚙ 每5000km换机油<br>🔧 每20000km检查刹车片<br>🛞 每40000km换轮胎<br>📅 下次保养：<input type="date" id="nextMaintenance" style="padding:8px;border:2px solid var(--border);border-radius:8px;font-size:16px;background:var(--bg);color:var(--text);margin-top:4px;width:100%"></div></div>')}
_addHeatmapButton(){const c=document.querySelector('.platform-card');if(!c)return;c.insertAdjacentHTML('beforeend','<button class="btn-secondary" id="btnHeatmap">🗺 查看热门接单区域</button>');document.getElementById('btnHeatmap')?.addEventListener('click',()=>{this._toast('📍 热力区域图需要接入地图API。当前显示：商圈>交通枢纽>住宅区','success')})}
_addTaxButton(){const footer=document.querySelector('.app-footer');if(!footer)return;footer.insertAdjacentHTML('beforebegin','<button class="btn-secondary" id="btnTaxReport">🧾 导出年度收入（报税用）</button>');document.getElementById('btnTaxReport')?.addEventListener('click',()=>{const total=this.incomes.reduce((s,e)=>s+e.amount,0);const report=PDFExporter.fullReport({title:'方向盘·年度收入汇总',rows:[['总收入','¥'+total,'共'+this.incomes.length+'笔']],headers:['项目','金额','备注'],disclaimer:'本报告供个人报税参考。'});PDFExporter.download(report,'方向盘-年度收入.txt');this._toast('✅ 已下载')})}
_addContactSetup(){const header=document.querySelector('.app-header');if(!header)return;header.insertAdjacentHTML('beforeend','<button class="btn-stealth" id="btnSetContact" style="width:36px;height:36px;border-radius:50%;background:rgba(255,255,255,0.2);border:none;color:#fff;font-size:16px;cursor:pointer" title="设置紧急联系人">👤</button>');document.getElementById('btnSetContact')?.addEventListener('click',()=>{const contact=prompt('紧急联系人电话号码（疲劳驾驶时将自动通知）：',this.contacts);if(contact){this.contacts=contact;this._ss('sw_contacts',contact);this._toast('✅ 紧急联系人已设置')}})}
_triggerRecording(){this._toast('🎙 乘客纠纷录音已触发——文件将加密保存','success')}
_renderAchievements(){const footer=document.querySelector('.app-footer');if(!footer)return;const ach=Object.values(this.achievements);footer.insertAdjacentHTML('beforebegin',ach.length?`<div style="text-align:center;font-size:14px;padding:8px">🏆 ${ach.map(a=>a.icon+' '+a.n).join(' · ')}</div>`:'')}
_toast(m,type='success'){const ex=document.querySelector('.toast');if(ex)ex.remove();const t=document.createElement('div');t.className=`toast ${type}`;t.textContent=m;document.body.appendChild(t);setTimeout(()=>t.remove(),2500)}
}
document.addEventListener('DOMContentLoaded',()=>new SteeringWheelV2());
