// 节拍器 v2.0 — 新增强制休息定时器+训练打卡+工厂评价+听力保护+法律测验+PDF报告+换厂决策+成就
class MetronomeV2{constructor(){this.rsi=new RSIAssessor();this.chemicals=new ChemicalLog();this.currentQ=0;this.exerciseStreak=this._ls('mt_streak',0);this.exercisesDone=this._ls('mt_exdone',[]);this.quizScore=this._ls('mt_quiz',0);this.restTimer=null;this.init()}
_ls(k,d){try{return JSON.parse(localStorage.getItem(k))||d}catch{return d}}
_ss(k,v){localStorage.setItem(k,JSON.stringify(v))}
init(){this._bind();this._renderExercises();this._renderChemicalLog();this._startRestTimer();this._renderFactoryRating();this._renderHearingProtection();this._addQuizButton();this._addReportButton();this._renderAchievements()}
_bind(){document.getElementById('btnRSIAssess')?.addEventListener('click',()=>this._startRSI());document.getElementById('btnCalcOvertime')?.addEventListener('click',()=>this._calcOvertime());document.getElementById('btnRecordChemical')?.addEventListener('click',()=>document.getElementById('chemModal').classList.remove('hidden'));document.getElementById('btnChemCancel')?.addEventListener('click',()=>document.getElementById('chemModal').classList.add('hidden'));document.getElementById('btnChemSave')?.addEventListener('click',()=>this._saveChemical());document.querySelectorAll('.modal-overlay').forEach(o=>o.addEventListener('click',e=>{if(e.target===o)o.classList.add('hidden')}))}
_startRSI(){this.currentQ=0;this.rsi.answers={};document.getElementById('rsiModal').classList.remove('hidden');this._showQ();this._ss('mt_rsi_count',(this._ls('mt_rsi_count',0))+1)}
_showQ(){const q=this.rsi.questions[this.currentQ];document.getElementById('rsiQuestion').textContent=`${this.currentQ+1}/${this.rsi.questions.length}: ${q.text}`;document.getElementById('rsiOptions').innerHTML=q.options.map((o,i)=>`<button class="rsi-option" data-score="${o.score}">${o.label}</button>`).join('');document.getElementById('rsiOptions').querySelectorAll('.rsi-option').forEach(b=>b.addEventListener('click',()=>{this.rsi.recordAnswer(q.id,parseInt(b.dataset.score));this._nextQ()}))}
_nextQ(){if(this.currentQ<this.rsi.questions.length-1){this.currentQ++;this._showQ()}else{document.getElementById('rsiModal').classList.add('hidden');this._showRSI()}}
_showRSI(){const r=this.rsi.assess();if(!r)return;const c=document.getElementById('rsiResult');c.hidden=false;c.innerHTML=`<div class="rsi-level ${r.level}"><div class="rsi-score">${r.total}/${r.max}</div><div class="rsi-label">${r.level==='low'?'✅ 低风险':r.level==='medium'?'⚠️ 中等':r.level==='high'?'🔴 高风险':'🚨 极高'}</div><div>重点：${r.bodyParts.join('、')}</div><div class="rsi-advice">${r.actions.map(a=>`<div>• ${a}</div>`).join('')}</div></div><button class="btn-secondary" style="margin-top:12px" onclick="location.reload()">🔄 重新评估</button>`}
_renderExercises(){const exs=[{icon:'🤲',name:'手腕伸展',desc:'手臂伸直手掌向上轻拉手指',count:'每手10s×3'},{icon:'🔄',name:'肩膀环绕',desc:'双肩画圈前后各10圈',count:'各10圈'},{icon:'🙆',name:'颈部侧屈',desc:'头缓慢向一侧倾斜',count:'每侧15s×2'},{icon:'🧘',name:'腰部扭转',desc:'坐姿身体缓慢向一侧扭转',count:'每侧×3'},{icon:'✊',name:'手指开合',desc:'握拳5s→打开手指',count:'重复10次'}];document.getElementById('exerciseList').innerHTML=exs.map((e,i)=>`<div class="exercise-item${this.exercisesDone.includes(i)?' completed':''}" onclick="this.classList.toggle('completed')"><div class="exercise-icon">${e.icon}</div><div class="exercise-info"><div class="exercise-name">${e.name}</div><div class="exercise-desc">${e.desc}</div></div><div class="exercise-timer">${e.count}</div></div>`).join('')}
_startRestTimer(){this.restTimer=setInterval(()=>{const h=new Date().getHours();if(h>=6&&h<=22){const toast=document.createElement('div');toast.className='toast success';toast.textContent='⏰ 该做预防训练了！每小时伸展2分钟。';document.body.appendChild(toast);setTimeout(()=>toast.remove(),3000)}},45*60000)}
_renderFactoryRating(){const footer=document.querySelector('.app-footer');if(!footer)return;footer.insertAdjacentHTML('beforebegin','<div class="card" style="border-left:5px solid #f59e0b"><div class="card-header"><span class="card-icon">🏭</span><h2>工厂条件匿名评价</h2></div><div id="factoryRating"><div style="font-size:15px;color:var(--text2)">匿名评价你所在工厂的温度/噪音/粉尘/管理。数据仅用于帮助其他工友做出换厂决策。</div></div><button class="btn-secondary" id="btnRateFactory">✏ 匿名评价</button></div>');document.getElementById('btnRateFactory')?.addEventListener('click',()=>{const t=prompt('温度评分(1-5):');const n=prompt('噪音评分(1-5):');const d=prompt('粉尘评分(1-5):');if(t){const rating={temp:parseInt(t),noise:parseInt(n),dust:parseInt(d),date:new Date().toISOString()};this._ss('mt_factory',rating);this._toast('✅ 匿名评价已保存')}})}
_renderHearingProtection(){const footer=document.querySelector('.app-footer');if(!footer)return;footer.insertAdjacentHTML('beforebegin','<div class="card" style="border-left:5px solid #8b5cf6"><div class="card-header"><span class="card-icon">👂</span><h2>听力保护</h2></div><div style="font-size:16px">⚡ 噪音环境：建议每2小时佩戴耳塞休息15分钟<br>⚡ 长期暴露>85dB可导致永久听力损伤<br>⚡ 每年做一次听力检查</div></div>')}
_addQuizButton(){const card=document.querySelector('.training-card');if(card)card.insertAdjacentHTML('beforeend','<button class="btn-secondary" id="btnLawQuiz">📝 劳动法知识测验</button>');document.getElementById('btnLawQuiz')?.addEventListener('click',()=>{const qs=[{q:'每月加班不得超过多少小时？',a:['24','36','48','72'],c:1},{q:'试用期最长几个月？',a:['3','6','9','12'],c:1},{q:'法定节假日加班几倍工资？',a:['1.5','2','3','4'],c:2}];const q=qs[Math.floor(Math.random()*qs.length)];const ans=prompt(`${q.q}\n${q.a.map((a,i)=>`${i+1}.${a}`).join('\n')}`);if(ans&&parseInt(ans)-1===q.c){this.quizScore++;this._ss('mt_quiz',this.quizScore);this._toast(`✅ 正确！累计答对 ${this.quizScore} 题`)}else{this._toast('❌ 错误。建议学习权益知识。','error')}})}
_addReportButton(){const footer=document.querySelector('.app-footer');if(!footer)return;footer.insertAdjacentHTML('beforebegin','<button class="btn-secondary" id="btnMonthReport">📊 导出健康与加班报告</button>');document.getElementById('btnMonthReport')?.addEventListener('click',()=>{const chemicals=this.chemicals.getEntries();const report=PDFExporter.fullReport({title:'节拍器·月度健康报告',rows:chemicals.slice(0,10).map(c=>[c.name,String(c.duration)+'h',c.protection]),headers:['化学品','时长','防护'],disclaimer:'本报告自动生成。化学品暴露数据是职业病认定的重要证据。'});PDFExporter.download(report,'节拍器-月报.txt');this._toast('✅ 报告已下载')})}
_renderAchievements(){const footer=document.querySelector('.app-footer');if(!footer)return;const count=this._ls('mt_rsi_count',0);const ach=[];if(count>=1)ach.push('📋 首次RSI评估');if(count>=5)ach.push('🔬 定期监测');if(this.quizScore>=3)ach.push('📚 法律达人');footer.insertAdjacentHTML('beforebegin',ach.length?`<div style="text-align:center;font-size:14px;padding:8px">🏆 ${ach.join(' · ')}</div>`:'')}
_calcOvertime(){const s=parseFloat(document.getElementById('baseSalary').value)||0;const wd=parseFloat(document.getElementById('weekdayOT').value)||0;const we=parseFloat(document.getElementById('weekendOT').value)||0;const hd=parseFloat(document.getElementById('holidayOT').value)||0;if(!s){this._toast('请填写月工资','error');return}const r=OvertimeCalculator.calculate(s,wd,we,hd);const c=document.getElementById('overtimeResult');c.hidden=false;c.innerHTML=`<div style="font-size:16px;color:var(--text2)">时薪：<strong>¥${r.hourlyRate}/h</strong></div>${r.breakdown.map(b=>`<div class="overtime-line"><span>${b.label}</span><span>${b.hours}h×¥${b.rate}=<strong>¥${b.amount}</strong></span></div>`).join('')}<div class="overtime-total">应得加班费合计：¥${r.total}</div>${r.tips.length?`<div style="margin-top:12px;padding:12px;background:var(--warning-bg);border-radius:8px;font-size:15px;line-height:1.8">${r.tips.map(t=>`<div>${t}</div>`).join('')}</div>`:''}`}
_saveChemical(){const n=document.getElementById('chemName').value.trim();const d=document.getElementById('chemDuration').value;const p=document.getElementById('chemProtection').value;if(!n){this._toast('请填写化学品名称','error');return}this.chemicals.addEntry(n,d,p);document.getElementById('chemModal').classList.add('hidden');document.getElementById('chemName').value='';this._renderChemicalLog();this._toast('✅ 已记录')}
_renderChemicalLog(){const e=this.chemicals.getEntries();document.getElementById('chemCount').textContent=e.length+'条';const c=document.getElementById('chemicalLog');if(!e.length){c.innerHTML='<div style="font-size:15px;color:var(--text2);text-align:center;padding:12px">化学品暴露记录是职业病认定的重要证据</div>';return}c.innerHTML=e.slice(0,10).map(en=>`<div class="chemical-item"><div class="chem-icon">🧪</div><div class="chem-info"><strong>${en.name}</strong>·${en.duration}h</div></div>`).join('')}
_toast(m,type='success'){const ex=document.querySelector('.toast');if(ex)ex.remove();const t=document.createElement('div');t.className=`toast ${type}`;t.textContent=m;document.body.appendChild(t);setTimeout(()=>t.remove(),2500)}
}
document.addEventListener('DOMContentLoaded',()=>new MetronomeV2());
